[project]
name = "computer-graphics-from-scratch"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "mypy>=2.3.1",
    "numpy>=2.5.3",
    "pillow>=12.3.0",
]

[tool.mypy]
python_version = "3.14"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = false
check_untyped_defs = true
